---
name: sync

"on":
  workflow_dispatch:
  schedule:
    - cron: '24 * * * *'

permissions: {}

jobs:
  gitlab_sync:
    permissions:
      contents: read
    uses: >-
      shared-common/gh-actions-shared/.github/workflows/gitlab-sync-core.yml@v0.0.40
    with:
      target-org: ${{ github.repository_owner }}
      target-profile: xf-secops
      shared-repo: shared-common/gh-actions-shared
      shared-ref: v0.0.40
      bws-version: ${{ vars.BWS_VERSION }}
      bws-sha256: ${{ vars.BWS_SHA256 }}
    secrets:
      BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
      BWS_PROJECT_ID: ${{ secrets.BWS_PROJECT_ID }}
